config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#welcome'
  resources :shops
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/shop.rb
class Shop < ApplicationRecord
    validates :corporate_name, :cnpj, :address, :city, :state, :manager, presence: true
    validates :cnpj, length: { in: 11..14 }
    validates :corporate_name, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    layout 'application_home'

    def welcome
        @shops = Shop.all
    end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
    layout 'application_user'

    def new
        @shop = Shop.new
    end

    def create
        @shop = Shop.new (params.require(:shop).permit(:corporate_name, :cnpj, :address, :city, :state, :manager))
        if @shop.save
            redirect_to root_path, notice: 'Loja Registrada Com Sucesso'
        else
            flash.now[:alert] = 'Não Foi Possível Registrar a Loja'
            render 'new'
        end
    end

    def edit
        @shop = Shop.find(params[:id])
    end

    def update
        @shop = Shop.find(params[:id])
        @shop.update(params.require(:shop).permit(:corporate_name, :cnpj, :address, :city, :state, :manager))
        redirect_to root_path
    end

    def destroy
        shop = Shop.find(params[:id])
        shop.delete
        redirect_to root_path, notice: 'Loja Deletada Com Sucesso'
    end

    def index
        @shops = Shop.all
    end

    def show
        @shop = Shop.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/welcome.html.erb
<% if user_signed_in?%>

    <div class="bodyhome">
        <div class="ls-list">
            <header class="ls-list-header">
                <div class="ls-list-title col-md-9">
                <a href="#" >Lista de Lojas</a>
                <small>Todas as Lojas Registradas  </small>
                </div>
                <div class="col-md-3 ls-txt-right">
                <%= link_to 'Administrar', shops_path, :class => "ls-btn-primary" %>
                </div>
            </header>
        </div>

        <div class="ls-list">
            <header class="ls-list-header">
                <div class="ls-list-title col-md-9">
                <a href="#" >Nova Loja</a>
                <small>Adicione Uma Nova Loja a Lista  </small>
                </div>
                <div class="col-md-3 ls-txt-right">
                <%= link_to 'Administrar', new_shop_path, :class => "ls-btn-primary" %>
                </div>
        </header>
        </div>

        <div class="ls-list">
            <header class="ls-list-header">
                <div class="ls-list-title col-md-9">
                <a href="#" >Lista de Registros</a>
                <small>Histórico de todas as lojas registradas até o momento   </small>
                </div>
                <div class="col-md-3 ls-txt-right">
                <a href="#" class="ls-btn-primary">Administrar</a>
                </div>
            </header>
        </div>

        <div class="ls-list">
            <header class="ls-list-header">
                <div class="ls-list-title col-md-9">
                <a href="#" >Lista de Gerentes</a>
                <small>Todos os gerentes e as lojas relacionadas  </small>
                </div>
                <div class="col-md-3 ls-txt-right">
                <a href="#" class="ls-btn-primary">Administrar</a>
                </div>
            </header>
        </div>
    </div>

<% else %>

<div class= "welcomescreen">
   <h2>Olá, antes de começar, é preciso logar</h1>
   <div class="loginbotton"><%= link_to 'LOGIN', user_session_path, :class => "ls-btn-primary" %></div>
</div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>APP DO RODRIGO</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="//assets.locaweb.com.br/locastyle/edge/stylesheets/locastyle.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
  </head>
  <body>
    <header>
    </header>
    <main>
      <div class="alerts_message">
      <p><%= flash[:notice] %></p>
      <p><%= flash[:alert] %></p>
      </div>
      <%= yield %>

      <script src="//assets.locaweb.com.br/locastyle/edge/javascripts/locastyle.js"></script>
    </main>
  </body>
</html>

app/views/layouts/application_home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>APP DO RODRIGO</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="//assets.locaweb.com.br/locastyle/edge/stylesheets/locastyle.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
  </head>
  <body>
    <header>
    </header>
    <main>
      <div class="ls-topbar">

  <!-- Barra de Notificações -->
  <div class="ls-notification-topbar">

    <!-- Links de apoio -->
    <div class="ls-alerts-list">
      <a href="#" class="ls-ico-bell-o" data-counter="8" data-ls-module="topbarCurtain" data-target="#ls-notification-curtain"><span>Notificações</span></a>
      <a href="#" class="ls-ico-bullhorn" data-ls-module="topbarCurtain" data-target="#ls-help-curtain"><span>Ajuda</span></a>
      <a href="#" class="ls-ico-question" data-ls-module="topbarCurtain" data-target="#ls-feedback-curtain"><span>Sugestões</span></a>
    </div>

    <!-- Dropdown com detalhes da conta de usuário -->
    <div data-ls-module="dropdown" class="ls-dropdown ls-user-account">
      <a href="#" class="ls-ico-user">
        <span class="ls-name">João</span>
        (fmolina)
      </a>
      <nav class="ls-dropdown-nav ls-user-menu">
        <ul>
          <li><a href="#">Meus dados</a></li>
          <li><a href="#">Faturas</a></li>
          <li><a href="#">Planos</a></li>
          <li><a href="#">Sair</a></li>
         </ul>
      </nav>
    </div>
  </div>

  <span class="ls-show-sidebar ls-ico-menu"></span>

  <!-- Nome do produto/marca -->
    <h1 class="ls-brand-name">
      <a href="#" class="ls-ico-earth">
        Nome do produto
      </a>
    </h1>
</div>

<main class="ls-main">


</main>

<aside class="ls-notification">
  <nav class="ls-notification-list" id="ls-notification-curtain">
    <h3 class="ls-title-2">Notificações</h3>
    <ul>
        <li class="ls-dismissable">
          <a href="#">Nam quo nisi voluptatem</a>
          <a href="#" data-ls-module="dismiss" class="ls-ico-close ls-close-notification"></a>
        </li>
        <li class="ls-dismissable">
          <a href="#">Porro aut dolorum ut tempore explicabo et non sit unde quas officiis ut</a>
          <a href="#" data-ls-module="dismiss" class="ls-ico-close ls-close-notification"></a>
        </li>
        <li class="ls-dismissable">
          <a href="#">Error odio explicabo et consequatur quasi sunt</a>
          <a href="#" data-ls-module="dismiss" class="ls-ico-close ls-close-notification"></a>
        </li>
        <li class="ls-dismissable">
          <a href="#">Ea et numquam dolor quasi qui</a>
          <a href="#" data-ls-module="dismiss" class="ls-ico-close ls-close-notification"></a>
        </li>
        <li class="ls-dismissable">
          <a href="#">Vitae temporibus tempore rerum est iure rerum</a>
          <a href="#" data-ls-module="dismiss" class="ls-ico-close ls-close-notification"></a>
        </li>
    </ul>
    <p class="ls-no-notification-message">Não há notificações.</p>
  </nav>
  <nav class="ls-notification-list" id="ls-help-curtain">
    <h3 class="ls-title-2">Feedback</h3>
    <ul>
        <li><a href="#">> velit consectetur cum rerum dolores officiis</a></li>
        <li><a href="#">> similique id at doloribus consequatur non</a></li>
    </ul>
  </nav>
  <nav class="ls-notification-list" id="ls-feedback-curtain">
    <h3 class="ls-title-2">Ajuda</h3>
    <ul>
      <li><a href="#">> Guia</a></li>
      <li><a href="#">> Wiki</a></li>
    </ul>
  </nav>
</aside>

<aside class="ls-sidebar">
  <div data-ls-module="dropdown" class="ls-dropdown ls-user-account ls-active">
    <a href="#" class="ls-ico-user">
      <span class="ls-name">Franco Molina dos Santos Silva</span>
      (fmolina)
    </a>
    <nav class="ls-dropdown-nav ls-user-menu" aria-hidden="true">
      <ul>
        <li><a href="#" role="option">Meus dados</a></li>
        <li><a href="#" role="option">Faturas</a></li>
        <li><a href="#" role="option">Planos</a></li>
       </ul>
       <a href="#" class="ls-btn-logout" role="combobox" aria-expanded="false">Sair</a>
    </nav>
  </div>
  <h1 class="ls-brand-name ls-ico-earth"><a href="home">Nome do produto</a></h1>
</aside>
    
      <%= flash[:notice] %></p>
      <%= flash[:alert] %></p>
      <%= yield %>

      <script src="//assets.locaweb.com.br/locastyle/edge/javascripts/locastyle.js"></script>
    </main>
  </body>
</html>

app/views/layouts/application_user.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>APP DO RODRIGO</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="//assets.locaweb.com.br/locastyle/edge/stylesheets/locastyle.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
  </head>
  <body>
    <header>
    </header>
    <main>

    <div class="ls-topbar">

  <!-- Barra de Notificações -->
  <div class="ls-notification-topbar">

    <!-- Links de apoio -->
    <div class="ls-alerts-list">
      <a href="#" class="ls-ico-bell-o" data-counter="8" data-ls-module="topbarCurtain" data-target="#ls-notification-curtain3"><span>Notificações</span></a>
      <a href="#" class="ls-ico-bullhorn" data-ls-module="topbarCurtain" data-target="#ls-help-curtain3"><span>Ajuda</span></a>
      <a href="#" class="ls-ico-question" data-ls-module="topbarCurtain" data-target="#ls-feedback-curtain3"><span>Sugestões</span></a>
    </div>

    <!-- Dropdown com detalhes da conta de usuário -->
    <div data-ls-module="dropdown" class="ls-dropdown ls-user-account">
      <a href="#" class="ls-ico-user">
        <span class="ls-name">João</span>
        (fmolina)
      </a>
      <nav class="ls-dropdown-nav ls-user-menu">
        <ul>
          <li><a href="#">Meus dados</a></li>
          <li><a href="#">Faturas</a></li>
          <li><a href="#">Planos</a></li>
          <li><a href="#">Sair</a></li>
         </ul>
      </nav>
    </div>
  </div>

  <span class="ls-show-sidebar ls-ico-menu"></span>

  <a href="#" class="ls-go-next"><span class="ls-text">Voltar à lista de serviços</span></a>

  <h1 class="ls-brand-name">
    <a href="#" class="ls-ico-earth">
      <small>Nome do produto</small>
      identificador da unidade
    </a>
  </h1>

</div>

<main class="ls-main"></main>

<aside class="ls-sidebar">
  <div data-ls-module="dropdown" class="ls-dropdown ls-user-account">
    <a href="#" class="ls-ico-user">
      <span class="ls-name">Franco Molina dos Santos Silva</span>
      (fmolina)
    </a>
    <nav class="ls-dropdown-nav ls-user-menu" aria-hidden="true">
      <ul>
        <li><a href="#" role="option">Meus dados</a></li>
        <li><a href="#" role="option">Faturas</a></li>
        <li><a href="#" role="option">Planos</a></li>
       </ul>
       <a href="#" class="ls-btn-logout" role="combobox" aria-expanded="false">Sair</a>
    </nav>
  </div>
  <div class="ls-sidebar-inner">
    <a href="/" class="ls-go-prev"><span class="ls-text">Voltar à lista de serviços</span></a>
    <nav class="ls-menu">
      <ul>
        <li class="ls-active"><a href="#" class="ls-ico-dashboard">Dashboard</a></li>
        <li><a href="#" class="ls-ico-stats">Item de menu</a></li>
        <li><a href="#" class="ls-ico-image">Item de menu</a></li>
        <li class="ls-submenu">
          <a href="#" class="ls-ico-cog">Item de menu pai</a>
          <ul role="menu">
            <li><a class="ls-submenu-item" href="#">Item de submenu</a></li>
            <li><a class="ls-submenu-item" href="#">Item de submenu</a></li>
            <li><a class="ls-submenu-item" href="#">Item de submenu</a></li>
          </ul>
        </li>
      </ul>
    </nav>
  </div>
</aside>


<aside class="ls-notification">
  <nav class="ls-notification-list" id="ls-notification-curtain3">
    <h3 class="ls-title-2">Notificações</h3>
    <ul>
        <li class="ls-dismissable">
          <a href="#">Sed architecto doloribus nam sed optio labore deserunt</a>
          <a href="#" data-ls-module="dismiss" class="ls-ico-close ls-close-notification"></a>
        </li>
        <li class="ls-dismissable">
          <a href="#">Vero voluptas et eveniet recusandae</a>
          <a href="#" data-ls-module="dismiss" class="ls-ico-close ls-close-notification"></a>
        </li>
        <li class="ls-dismissable">
          <a href="#">Omnis velit sint autem molestias voluptatem laudantium quis ut atque ut reiciendis et quo</a>
          <a href="#" data-ls-module="dismiss" class="ls-ico-close ls-close-notification"></a>
        </li>
        <li class="ls-dismissable">
          <a href="#">Quia voluptas non natus est quis</a>
          <a href="#" data-ls-module="dismiss" class="ls-ico-close ls-close-notification"></a>
        </li>
        <li class="ls-dismissable">
          <a href="#">Non neque maiores libero aut officiis est laudantium velit ipsum blanditiis voluptates</a>
          <a href="#" data-ls-module="dismiss" class="ls-ico-close ls-close-notification"></a>
        </li>
    </ul>
    <p class="ls-no-notification-message">Não há notificações.</p>
  </nav>
  <nav class="ls-notification-list" id="ls-help-curtain3">
    <h3 class="ls-title-2">Feedback</h3>
    <ul>
        <li><a href="#">> exercitationem fugit assumenda non consequatur minus</a></li>
        <li><a href="#">> sit odio sit nesciunt nihil facere</a></li>
    </ul>
  </nav>
  <nav class="ls-notification-list" id="ls-feedback-curtain3">
    <h3 class="ls-title-2">Ajuda</h3>
    <ul>
      <li><a href="#">> Guia</a></li>
      <li><a href="#">> Wiki</a></li>
    </ul>
  </nav>
</aside>

      <%= flash[:notice] %></p>
      <%= flash[:alert] %></p>
      <%= yield %>

      <script src="//assets.locaweb.com.br/locastyle/edge/javascripts/locastyle.js"></script>
    </main>
  </body>
</html>

app/views/shops/edit.html.erb

        <h2> Edite Sua Loja Aqui </h2><br>

        <%= form_for @shop do |s|%>
            <%= s.label :corporate_name, 'Razão Social'%>
            <%= s.text_field :corporate_name %>
            <%= s.label :cnpj, 'CNPJ'%>
            <%= s.number_field :cnpj%>
            <%= s.label :address, 'Endereço'%>
            <%= s.text_field :address%>
            <%= s.label :city, 'Cidade'%>
            <%= s.text_field :city%>
            <%= s.label :state, 'Estado'%>
            <%= s.text_field :state %>
            <%= s.label :manager, 'Gerente'%>
            <%= s.text_field :manager %>
            <%= s.submit 'Registrar Edição'%>
        <% end %>
   

app/views/shops/index.html.erb
<div class="bodyindex">
    <table class="ls-table">
    <thead>
            <tr>
            <th class="hidden-xs">Razão Social</th>
            <th>CNPJ</th>
            <th class="hidden-xs">Endereço</th>
            <th>Cidade / Estado</th>
            <th class="hidden-xs">Gerente</th>
            <th>Ação</th>
            </tr>
        </thead>
        <tbody>
            <% @shops.each do |shop| %>
                <tr>
                <td class="hidden-xs"><%= shop.corporate_name %></td>
                <td><%= shop.cnpj %></td>
                <td class="hidden-xs"><%= shop.address %></td>
                <td><%= shop.city %> / <%= shop.state %></td>
                <td><%= shop.manager %></td>
                <td class="hidden-xs"><%= link_to 'Editar', edit_shop_path(shop) %>
                    <%= button_to 'Apagar', shop_path(shop), method: :delete %></td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/shops/new.html.erb
<div class="newshop">

    <h2> Cadastre Sua Loja Aqui </h2><br>

    <%= form_for Shop.new do |s|%>

    <% if @shop.errors.any? %>
        <span>Verifique os Campos Abaixo:</span><br><br>
    <% end %>

        <%= s.label :corporate_name, 'Razão Social'%><br>
        <%= s.text_field :corporate_name %><br>
        <% @shop.errors.full_messages_for(:corporate_name).each do |msg| %>
            <li><%= "Esse Campo deve ser preenchido" %></li>
        <% end %>
        <%= s.label :cnpj, 'CNPJ'%><br>
        <%= s.number_field :cnpj%><br>
        <% @shop.errors.full_messages_for(:cnpj).each do |msg| %>
            <li><%= "Esse Campo deve ser preenchido" %></li>
        <% end %>
        <%= s.label :address, 'Endereço'%><br>
        <%= s.text_field :address%><br>
        <% @shop.errors.full_messages_for(:address).each do |msg| %>
            <li><%= "Esse Campo deve ser preenchido" %></li>
        <% end %>
        <%= s.label :city, 'Cidade'%><br>
        <%= s.text_field :city%><br>
        <% @shop.errors.full_messages_for(:city).each do |msg| %>
            <li><%= "Esse Campo deve ser preenchido" %></li>
        <% end %>
        <%= s.label :state, 'Estado'%><br>
        <%= s.text_field :state %><br>
        <% @shop.errors.full_messages_for(:state).each do |msg| %>
            <li><%= "Esse Campo deve ser preenchido" %></li>
        <% end %>
        <%= s.label :manager, 'Gerente'%><br>
        <%= s.text_field :manager %><br>
        <% @shop.errors.full_messages_for(:manager).each do |msg| %>
            <li><%= "Esse Campo deve ser preenchido" %></li>
        <% end %>
        <%= s.submit 'Registrar'%>
    <% end %>
    
</div>

app/views/shops/show.html.erb
<%= @shop.corporate_name %>
<%= @shop.cnpj %>
<%= @shop.address %>
<%= @shop.city %>
<%= @shop.state %>
<%= @shop.manager %>
<%= link_to 'Editar', edit_shop_path(shop) %>
<%= button_to 'Apagar', shop_path(shop), method: :delete %><br>